steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Push
  args:
  - 'builds'
  - 'submit'
  - '--tag'
  - 'gcr.io/$PROJECT_ID/urlinsane-ui'
  waitFor:
  - '-'
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args:
  - 'beta'
  - 'run'
  - 'deploy'
  - '--region=us-central1'
  - 'urlinsane-ui'
  - '--image'
  - 'gcr.io/$PROJECT_ID/urlinsane-ui'
  - '--allow-unauthenticated'
  - '--memory=256Mi'
  - '--concurrency=2'
  - '--update-env-vars'
  - 'WEBSOCKET_PROTOCOL=ws,WEBSOCKET_HOST=http://api.urlinsane.com,WEBSOCKET_PORT=80'
  waitFor:
  - 'Push'
